# Generated by Django 6.0.3 on 2026-04-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
