# Generated by Django 6.0.3 on 2026-04-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria')),
            ],
            options={
                'db_table': 'tipos_despesa',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_orcado', models.FloatField()),
                ('valor_realizado', models.FloatField()),
                ('data', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.projeto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodespesa')),
            ],
            options={
                'db_table': 'despesas',
            },
        ),
    ]
