# Generated by Django 6.0.3 on 2026-04-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_categoria_tipodespesa_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(default='Custeio', max_length=20),
            preserve_default=False,
        ),
    ]
